---
title: "Models"
author: "Mercedes Cullen"
date: "2025-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown

```{r load data}
state_data <- read.csv("state_data.csv")
```

## Creating total funding variable 


```{r state funding variable, echo=FALSE}
state_data <- mutate(state_data,
                     funding_total = coc +
                       cdbg_entitlement +
                       elderly +
                       grrp_comp +
                       grrp_elements +
                       grrp_leading +
                       home + 
                       hud_disability +
                       hud_esg +
                       hud_hopwa +
                       hud_htf + 
                       public_hsg +
                       public_hsg_cap + 
                       s8_project
                    )
```

```{r view column names}
colnames(state_data)
```

```{r}
states_clean <- state_data |>
  rename(
    homeless = `Overall Homeless`
  )
states_clean
```


## Building models for States 

```{r model 1}
model1 <- lm(homeless ~ funding_total, data = states_clean)
summary(model1) 
```

```{r residuals plot}
plot(model1$fitted.values, model1$residuals,
     xlab = "Fitted Values",
     ylab = "Residuals",
     main = "Residuals vs Fitted")

abline(h = 0, col = "red", lty = 2)
```

```{r confidence intervals}
predict(model1, interval = "confidence")
```

## Building Models for County

```{r import data}
county_data <- read_csv("county_data.csv")
```

```{r rename county variable}
county_clean <- county_data |>
  rename(
    homeless = `Overall Homeless`
  )
county_clean
```

```{r county model building}
county_model1 <- lm(homeless ~ funding_tot, data = county_clean)
summary(county_model1) 
```

```{r county residuals}
plot(county_model1$fitted.values, county_model1$residuals,
     xlab = "Fitted Values",
     ylab = "Residuals",
     main = "Residuals vs Fitted")

abline(h = 0, col = "red", lty = 2)
```

```{r county residuals}
predict(county_model1, interval = "confidence")
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
