library(tidyverse)

sind <- read_csv("table4_state-indicator.csv")
spro <- read_csv("table2_stateprogram.csv", 
                 col_types = cols(GEOID = col_character()))
spit <- read_csv("2024-PIT-Counts-by-State.csv")
shic <- read_csv("2024-HIC-Counts-by-State.csv", 
                                      col_types = cols(`Total Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...6` = col_number(), 
                                                       `Total Year-Round Beds (TH)...7` = col_number(), 
                                                       `Total Year-Round Beds (SH)...8` = col_number(), 
                                                       `Total Units for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households without Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Youth Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...15` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES)` = col_number(), 
                                                       `Total Seasonal Beds (ES)` = col_number(), 
                                                       `Total Overflow Beds (ES)` = col_number(), 
                                                       `Total Units for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households without Children (ES)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES)` = col_number(), 
                                                       `Dedicated Youth Beds (ES)` = col_number(), 
                                                       `Total Year-Round Beds (TH)...27` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (TH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (TH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (TH)` = col_number(), 
                                                       `Total Units for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households without Children (TH)` = col_number(), 
                                                       `Total Beds for Households with only Children (TH)` = col_number(), 
                                                       `Dedicated Veteran Beds (TH)` = col_number(), 
                                                       `Dedicated Youth Beds (TH)` = col_number(), 
                                                       `Total Year-Round Beds (SH)...37` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (SH)` = col_number(), 
                                                       `Total Units for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households without Children (SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (SH)` = col_number(), 
                                                       `Dedicated Youth Beds (SH)` = col_number(), 
                                                       `Total Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (RRH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (RRH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Units for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households without Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with only Children (RRH)` = col_number(), 
                                                       `Dedicated Veteran Beds (RRH)` = col_number(), 
                                                       `Dedicated Youth Beds (RRH)` = col_number(), 
                                                       `Total Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (PSH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (PSH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Units for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households without Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with only Children (PSH)` = col_number(), 
                                                       `Dedicated Veteran Beds (PSH)` = col_number(), 
                                                       `Dedicated Youth Beds (PSH)` = col_number(), 
                                                       `Dedicated Chronically Homeless Beds (PSH)` = col_number(), 
                                                       `Total Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (OPH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (OPH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Units for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households without Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with only Children (OPH)` = col_number(), 
                                                       `Dedicated Veteran Beds (OPH)` = col_number(), 
                                                       `Dedicated Youth Beds (OPH)` = col_number()), 
                                      skip = 1)

view(shic)
