---
title: "Lab Name"
author: "Author Name"
date: "`r Sys.Date()`"
output: github_document
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
```

### Exercise 1

Insert any text here.

```{State data}

sind <- read_csv("table4_state-indicator.csv")
spro <- read_excel("table2_stateprogram redo.xlsx")
spit <- read_csv("2024-PIT-Counts-by-State.csv")
shic <- read_csv("2024-HIC-Counts-by-State.csv", 
                                      col_types = cols(`Total Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...6` = col_number(), 
                                                       `Total Year-Round Beds (TH)...7` = col_number(), 
                                                       `Total Year-Round Beds (SH)...8` = col_number(), 
                                                       `Total Units for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households without Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Youth Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...15` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES)` = col_number(), 
                                                       `Total Seasonal Beds (ES)` = col_number(), 
                                                       `Total Overflow Beds (ES)` = col_number(), 
                                                       `Total Units for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households without Children (ES)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES)` = col_number(), 
                                                       `Dedicated Youth Beds (ES)` = col_number(), 
                                                       `Total Year-Round Beds (TH)...27` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (TH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (TH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (TH)` = col_number(), 
                                                       `Total Units for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households without Children (TH)` = col_number(), 
                                                       `Total Beds for Households with only Children (TH)` = col_number(), 
                                                       `Dedicated Veteran Beds (TH)` = col_number(), 
                                                       `Dedicated Youth Beds (TH)` = col_number(), 
                                                       `Total Year-Round Beds (SH)...37` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (SH)` = col_number(), 
                                                       `Total Units for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households without Children (SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (SH)` = col_number(), 
                                                       `Dedicated Youth Beds (SH)` = col_number(), 
                                                       `Total Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (RRH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (RRH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Units for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households without Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with only Children (RRH)` = col_number(), 
                                                       `Dedicated Veteran Beds (RRH)` = col_number(), 
                                                       `Dedicated Youth Beds (RRH)` = col_number(), 
                                                       `Total Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (PSH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (PSH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Units for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households without Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with only Children (PSH)` = col_number(), 
                                                       `Dedicated Veteran Beds (PSH)` = col_number(), 
                                                       `Dedicated Youth Beds (PSH)` = col_number(), 
                                                       `Dedicated Chronically Homeless Beds (PSH)` = col_number(), 
                                                       `Total Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (OPH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (OPH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Units for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households without Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with only Children (OPH)` = col_number(), 
                                                       `Dedicated Veteran Beds (OPH)` = col_number(), 
                                                       `Dedicated Youth Beds (OPH)` = col_number()), 
                                      skip = 1)


# programs to look at: coc, cdbg_entitlement, elderly, grrp_comp, grrp_elements, grrp_leading, hvc, home, 
# hud_disability, hud_esg, hud_hopwa, hud_htf, public_hsg, public_hsg_cap, s8_project

# indicators to look at: GEOID, NAME, total_pop, ALAND, AWATER, percent_urban, percent_rural, percent_poc,
# poverty_rate, pop_density, med_hh_income, employment_access_index, housing_cost_burden, overcrowded_housing,
# vacancy_rate, homelessness, homelessness, incomplete_plumbing, incomplete_kitchen, housing_units, permits,
# capacity_housing, hud_pbs8, hud_hcv, hud_202, hud_ph, age_under_18, age_over_64



spro_cut <- spro |>
  select(state, 
         GEOID, 
         coc, 
         cdbg_entitlement, 
         elderly, 
         grrp_comp, 
         grrp_elements, 
         grrp_leading, 
         home, 
         hud_disability, 
         hud_esg, 
         hud_hopwa, 
         hud_htf, 
         public_hsg, 
         public_hsg_cap, 
         s8_project)


sind_cut <- sind |>
  select(GEOID, 
         NAME, 
         total_pop, 
         ALAND, 
         AWATER, 
         percent_urban, 
         percent_rural, 
         percent_poc,
         poverty_rate,
         pop_density, 
         med_hh_income, 
         employment_access_index, 
         housing_cost_burden, 
         overcrowded_housing,
         vacancy_rate,
         incomplete_plumbing, 
         incomplete_kitchen, 
         housing_units, 
         permits,
         capacity_housing, 
         hud_pbs8, 
         hud_hcv, 
         hud_202, 
         hud_ph, 
         age_under_18, 
         age_over_64)

sind_cut$GEOID <- as.numeric(sind_cut$GEOID)

spit_cut <- spit |>
  select(State,
         `Number of CoCs`,
         `Overall Homeless`,
         `Overall Homeless - Under 18`,
         `Overall Homeless - Age 18 to 24`,
         `Overall Homeless - Age 25 to 34`,
         `Overall Homeless - Age 35 to 44`,
         `Overall Homeless - Age 45 to 54`,
         `Overall Homeless - Age 55 to 64`,
         `Overall Homeless - Over 64`,
         `Overall Homeless - Woman`,
         `Overall Homeless - Man`,
         `Overall Homeless - Transgender`,
         `Overall Homeless - Non Binary`,
         `Overall Homeless - More Than One Gender`,
         `Overall Homeless - Gender Questioning`,
         `Overall Homeless - Culturally Specific Identity`,
         `Overall Homeless - Different Identity`,
         `Overall Homeless - Non-Hispanic/Latina/e/o`,
         `Overall Homeless - Hispanic/Latina/e/o`,
         `Overall Homeless - Asian or Asian American`,
         `Overall Homeless - Black, African American, or African`,
         `Overall Homeless - Middle Eastern or North African`,
         `Overall Homeless - White`,
         `Overall Homeless - Native Hawaiian or Other Pacific Islander`,
         `Overall Homeless Veterans`,
         `Overall Chronically Homeless`,
         `Overall Homeless People in Families`,
         `Overall Homeless Individuals`,
         `Overall Homeless Unaccompanied Youth (Under 25)`,
         `Overall Homeless Parenting Youth (Under 25)`,
         `Sheltered Total Homeless`,
         `Sheltered ES Homeless`,
         `Sheltered TH Homeless`,
         `Sheltered SH Homeless`,
         `Unsheltered Homeless`
         )

shic_cut <- shic |>
  select(State,
         `Total Year-Round Beds (ES, TH, SH)`,
         `Total Year-Round Beds (ES)...6`,
         `Total Year-Round Beds (TH)...7`,
         `Total Year-Round Beds (SH)...8`,
         `Total Year-Round Beds (OPH)`,
         `Total Year-Round Beds (PSH)`,
         `Total Year-Round Beds (RRH)`)



nohome <- shic_cut |>
  left_join(spit_cut, by=c("State" = "State")) |>
  arrange(State)

program <- spro_cut |>
  left_join(sind_cut, by=c("GEOID" = "GEOID"))

sdat <- program |>
  left_join(nohome, by=c("state" = "State"))

sdat <- mutate(sdat,
               funding_tot = coc + 
                 cdbg_entitlement +
                 elderly +
                 grrp_comp +
                 grrp_elements +
                 grrp_leading +
                 home +
                 hud_disability +
                 hud_esg +
                 hud_hopwa +
                 hud_htf +
                 public_hsg +
                 public_hsg_cap +
                 s8_project)

write.csv(sdat, file = "~/Data and Society/data_and_society/state_data.csv")

```

### Exercise 2

...

```{r}

cind <- read_csv("table3_county-indicator.csv")
cpro <- read_excel("table4_countyprogram.csv")
cpit <- read_csv("2024-PIT-Counts-by-County.csv")
chic <- read_csv("2024-HIC-Counts-by-County.csv", 
                                      col_types = cols(`Total Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...6` = col_number(), 
                                                       `Total Year-Round Beds (TH)...7` = col_number(), 
                                                       `Total Year-Round Beds (SH)...8` = col_number(), 
                                                       `Total Units for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households without Children (ES, TH, SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES, TH, SH)` = col_number(), 
                                                       `Dedicated Youth Beds (ES, TH, SH)` = col_number(), 
                                                       `Total Year-Round Beds (ES)...15` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (ES)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (ES)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (ES)` = col_number(), 
                                                       `Total Seasonal Beds (ES)` = col_number(), 
                                                       `Total Overflow Beds (ES)` = col_number(), 
                                                       `Total Units for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households with Children (ES)` = col_number(), 
                                                       `Total Beds for Households without Children (ES)` = col_number(), 
                                                       `Total Beds for Households with only Children (ES)` = col_number(), 
                                                       `Dedicated Veteran Beds (ES)` = col_number(), 
                                                       `Dedicated Youth Beds (ES)` = col_number(), 
                                                       `Total Year-Round Beds (TH)...27` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (TH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (TH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (TH)` = col_number(), 
                                                       `Total Units for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households with Children (TH)` = col_number(), 
                                                       `Total Beds for Households without Children (TH)` = col_number(), 
                                                       `Total Beds for Households with only Children (TH)` = col_number(), 
                                                       `Dedicated Veteran Beds (TH)` = col_number(), 
                                                       `Dedicated Youth Beds (TH)` = col_number(), 
                                                       `Total Year-Round Beds (SH)...37` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (SH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (SH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (SH)` = col_number(), 
                                                       `Total Units for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households with Children (SH)` = col_number(), 
                                                       `Total Beds for Households without Children (SH)` = col_number(), 
                                                       `Total Beds for Households with only Children (SH)` = col_number(), 
                                                       `Dedicated Veteran Beds (SH)` = col_number(), 
                                                       `Dedicated Youth Beds (SH)` = col_number(), 
                                                       `Total Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (RRH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (RRH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (RRH)` = col_number(), 
                                                       `Total Units for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with Children (RRH)` = col_number(), 
                                                       `Total Beds for Households without Children (RRH)` = col_number(), 
                                                       `Total Beds for Households with only Children (RRH)` = col_number(), 
                                                       `Dedicated Veteran Beds (RRH)` = col_number(), 
                                                       `Dedicated Youth Beds (RRH)` = col_number(), 
                                                       `Total Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (PSH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (PSH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (PSH)` = col_number(), 
                                                       `Total Units for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with Children (PSH)` = col_number(), 
                                                       `Total Beds for Households without Children (PSH)` = col_number(), 
                                                       `Total Beds for Households with only Children (PSH)` = col_number(), 
                                                       `Dedicated Veteran Beds (PSH)` = col_number(), 
                                                       `Dedicated Youth Beds (PSH)` = col_number(), 
                                                       `Dedicated Chronically Homeless Beds (PSH)` = col_number(), 
                                                       `Total Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Non-DV Year-Round Beds (OPH)` = col_number(), 
                                                       `Total HMIS Year-Round Beds (OPH)` = col_number(), 
                                                       `HMIS Participation Rate for Year-Round Beds (OPH)` = col_number(), 
                                                       `Total Units for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with Children (OPH)` = col_number(), 
                                                       `Total Beds for Households without Children (OPH)` = col_number(), 
                                                       `Total Beds for Households with only Children (OPH)` = col_number(), 
                                                       `Dedicated Veteran Beds (OPH)` = col_number(), 
                                                       `Dedicated Youth Beds (OPH)` = col_number()), 
                                      skip = 1)


# programs to look at: coc, cdbg_entitlement, elderly, grrp_comp, grrp_elements, grrp_leading, hvc, home, 
# hud_disability, hud_esg, hud_hopwa, hud_htf, public_hsg, public_hsg_cap, s8_project

# indicators to look at: GEOID, NAME, total_pop, ALAND, AWATER, percent_urban, percent_rural, percent_poc,
# poverty_rate, pop_density, med_hh_income, employment_access_index, housing_cost_burden, overcrowded_housing,
# vacancy_rate, homelessness, homelessness, incomplete_plumbing, incomplete_kitchen, housing_units, permits,
# capacity_housing, hud_pbs8, hud_hcv, hud_202, hud_ph, age_under_18, age_over_64



spro_cut <- spro |>
  select(state, 
         GEOID, 
         coc, 
         cdbg_entitlement, 
         elderly, 
         grrp_comp, 
         grrp_elements, 
         grrp_leading, 
         home, 
         hud_disability, 
         hud_esg, 
         hud_hopwa, 
         hud_htf, 
         public_hsg, 
         public_hsg_cap, 
         s8_project)


sind_cut <- sind |>
  select(GEOID, 
         NAME, 
         total_pop, 
         ALAND, 
         AWATER, 
         percent_urban, 
         percent_rural, 
         percent_poc,
         poverty_rate,
         pop_density, 
         med_hh_income, 
         employment_access_index, 
         housing_cost_burden, 
         overcrowded_housing,
         vacancy_rate,
         incomplete_plumbing, 
         incomplete_kitchen, 
         housing_units, 
         permits,
         capacity_housing, 
         hud_pbs8, 
         hud_hcv, 
         hud_202, 
         hud_ph, 
         age_under_18, 
         age_over_64)

sind_cut$GEOID <- as.numeric(sind_cut$GEOID)

spit_cut <- spit |>
  select(State,
         `Number of CoCs`,
         `Overall Homeless`,
         `Overall Homeless - Under 18`,
         `Overall Homeless - Age 18 to 24`,
         `Overall Homeless - Age 25 to 34`,
         `Overall Homeless - Age 35 to 44`,
         `Overall Homeless - Age 45 to 54`,
         `Overall Homeless - Age 55 to 64`,
         `Overall Homeless - Over 64`,
         `Overall Homeless - Woman`,
         `Overall Homeless - Man`,
         `Overall Homeless - Transgender`,
         `Overall Homeless - Non Binary`,
         `Overall Homeless - More Than One Gender`,
         `Overall Homeless - Gender Questioning`,
         `Overall Homeless - Culturally Specific Identity`,
         `Overall Homeless - Different Identity`,
         `Overall Homeless - Non-Hispanic/Latina/e/o`,
         `Overall Homeless - Hispanic/Latina/e/o`,
         `Overall Homeless - Asian or Asian American`,
         `Overall Homeless - Black, African American, or African`,
         `Overall Homeless - Middle Eastern or North African`,
         `Overall Homeless - White`,
         `Overall Homeless - Native Hawaiian or Other Pacific Islander`,
         `Overall Homeless Veterans`,
         `Overall Chronically Homeless`,
         `Overall Homeless People in Families`,
         `Overall Homeless Individuals`,
         `Overall Homeless Unaccompanied Youth (Under 25)`,
         `Overall Homeless Parenting Youth (Under 25)`,
         `Sheltered Total Homeless`,
         `Sheltered ES Homeless`,
         `Sheltered TH Homeless`,
         `Sheltered SH Homeless`,
         `Unsheltered Homeless`
         )

shic_cut <- shic |>
  select(State,
         `Total Year-Round Beds (ES, TH, SH)`,
         `Total Year-Round Beds (ES)...6`,
         `Total Year-Round Beds (TH)...7`,
         `Total Year-Round Beds (SH)...8`,
         `Total Year-Round Beds (OPH)`,
         `Total Year-Round Beds (PSH)`,
         `Total Year-Round Beds (RRH)`)



nohome <- shic_cut |>
  left_join(spit_cut, by=c("State" = "State")) |>
  arrange(State)

program <- spro_cut |>
  left_join(sind_cut, by=c("GEOID" = "GEOID"))

sdat <- program |>
  left_join(nohome, by=c("state" = "State"))

sdat <- mutate(sdat,
               funding_tot = coc + 
                 cdbg_entitlement +
                 elderly +
                 grrp_comp +
                 grrp_elements +
                 grrp_leading +
                 home +
                 hud_disability +
                 hud_esg +
                 hud_hopwa +
                 hud_htf +
                 public_hsg +
                 public_hsg_cap +
                 s8_project)

write.csv(sdat, file = "~/Data and Society/data_and_society/state_data.csv")


```

### Exercise 3